// Autogenerated from Pigeon (v22.4.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "network_connectivity_api.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface nullNetworkConnectivityApiPigeonCodecReader : FlutterStandardReader
@end
@implementation nullNetworkConnectivityApiPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface nullNetworkConnectivityApiPigeonCodecWriter : FlutterStandardWriter
@end
@implementation nullNetworkConnectivityApiPigeonCodecWriter
- (void)writeValue:(id)value {
  {
    [super writeValue:value];
  }
}
@end

@interface nullNetworkConnectivityApiPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation nullNetworkConnectivityApiPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[nullNetworkConnectivityApiPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[nullNetworkConnectivityApiPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *nullGetNetworkConnectivityApiCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    nullNetworkConnectivityApiPigeonCodecReaderWriter *readerWriter = [[nullNetworkConnectivityApiPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpNetworkConnectivityApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NetworkConnectivityApi> *api) {
  SetUpNetworkConnectivityApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpNetworkConnectivityApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NetworkConnectivityApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.contacts_app.NetworkConnectivityApi.isNetworkConnected", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:nullGetNetworkConnectivityApiCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isNetworkConnectedWithError:)], @"NetworkConnectivityApi api (%@) doesn't respond to @selector(isNetworkConnectedWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isNetworkConnectedWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
