// Autogenerated from Pigeon (v22.4.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *nullGetNetworkConnectivityApiCodec(void);

@protocol NetworkConnectivityApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isNetworkConnectedWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpNetworkConnectivityApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NetworkConnectivityApi> *_Nullable api);

extern void SetUpNetworkConnectivityApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NetworkConnectivityApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
